### ISSUE TITLE
Why is the image captioning score on MS-COCO not measured on full validation set, but only on a subset? 

### ISSUE THREAD

**Issue by jmkim0309** [yxuansu/MAGIC#2]
About the image captioning results on MS-COCO, I could reproduce exactly the same scores as presented in Table1 of the paper, by using the following result file. (https://github.com/yxuansu/MAGIC/blob/main/image_captioning/inference_result/mscoco/magic_result.json)
However, this file only contains results of 4982 images, while the number of full validation images is about 40k. 
Why is the image captioning score on MS-COCO not measured on full validation set, but only on a subset?

**Comment by yxuansu** [comment]
> About the image captioning results on MS-COCO, I could reproduce exactly the same scores as presented in Table1 of the paper, by using the following result file. (https://github.com/yxuansu/MAGIC/blob/main/image_captioning/inference_result/mscoco/magic_result.json) However, this file only contains results of 4982 images, while the number of full validation images is about 40k. Why is the image captioning score on MS-COCO not measured on full validation set, but only on a subset?

Hi @khy0809, 

We evaluate our model following the Karpathy split which you can find here (https://www.kaggle.com/datasets/shtvkumar/karpathy-splits). The magic_result.json contains the test set predictions on MS-COCO. In the Karpathy split, the number of test cases is 5000. The reason why our result contains 4982 instances not 5000 is that a few images (in our case 18 images) cause errors when feeding into the off-the-shelf CLIP model. 

Hope my response can help you :-)

**Comment by jmkim0309** [comment]
Ok, now it is clear to me. Thank you!

2022년 6월 1일 (수) 오후 4:33, Yixuan Su ***@***.***>님이 작성:

**Comment by yhlleo** [comment]
@yxuansu @khy0809  To avoid the loading issue, the code [here](https://github.com/yxuansu/MAGIC/blob/main/image_captioning/inference_magic.py#L116) can be revised to:

```
            image_instance = Image.open(image_full_path).convert("RGB")
```

Sometimes, some PNG images are in the format of "RGBA", where the loaded images are 4-channels. It is better to discard the alpha channel.
