### ISSUE TITLE
is there anybody reproduce this methods with other LM/VLM?

### ISSUE THREAD

**Issue by 5joon2** [yxuansu/MAGIC#5]
Thanks to share this great work :) 

I have tried to reproduce this methods with my own LM(gpt-3)/VLM(CLIP). However, the quality is significantly inferior to the example you provided.
<img width="592" alt="스크린샷 2022-10-12 오전 9 11 19" src="https://user-images.githubusercontent.com/95912230/195220607-1e560c16-1bbd-44fd-9c69-37fb225f0e2d.png">

is there anybody reproduce this methods with your own LM/VLM ?
or
is there any implementation detail when I use my own LM/VLM ?

**Comment by yxuansu** [comment]
Hi @5joon2 -- Has your LM been adapted to the captioning domain (via unsupervised learning) as described in our paper?

Also, for different LMs, you should adapt the hyperparameters in magic search (i.e. $\alpha$ and $\beta$) accordingly.  I wonder have you tried to adapt them or just used our settings with your own model?

**Comment by 5joon2** [comment]
@yxuansu LM was not adapted to captioning and I just used default hyperparameters. Maybe I have to adapt the model to captioning and find optimal hyperparameters also. Thanks I will share the results later!
